#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore
picom -b &
lxsession &
polybar mybar &
polybar mybar2 &
polybar mybar3 &
bspc monitor -d I II III IV V VI VII 

bspc config border_width         3.5
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
#focus follow mouse pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config gapless_monocle      true
bspc config bottom_padding -7
bspc config top_padding -2
bspc config left_padding -5
bspc config right_padding -5

bspc config focused_border_color "#5B99C2"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Nitrogen state=floating center=true
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
